xpRate: 2.0
enableXpRateMultipliers: false
xpRateMultipliers: [1, 3, 5, 9]
membersOnlyMode: false
enableTutorialIsland: false
enablePartyRoom: true
enableClueScrolls: true
enableAdminTrade: false
enableAdminSell: false
respawnCoordinatesX: 3222
respawnCoordinatesY: 3218
saveIntervalSeconds: 120
enforceItemRequirements: true
