serverName: "2006PranScape"
guiEnabled: false
serverDebugEnabled: false
fileServer: true
httpPort: 8080
jaggrabPort: 43595
fileServerPort: 43594
worldId: 1
maxPlayer: 20
timeout: 60
enableCycleLogging: true
cycleLoggingTick: 10
